version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies (none for now)
  build:
    commands:
      - echo Build started on `date`
      - echo No build commands needed yet
artifacts:
  files:
    - "**/*"
